apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-hpas
rules:
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - patch
